[llvm]
link-shared = true

[build]
build = "x86_64-unknown-linux-gnu"
target = ["x86_64-unknown-linux-gnu"]
vendor = true
extended = true
sanitizers = true
profiler = true

[install]
prefix = "/usr"
sysconfdir = "/usr/share/defaults/etc"

[rust]
optimize = true
default-linker = "/usr/bin/clang"
channel = "stable"
description = "Serpent OS"
rpath = false
llvm-libunwind = 'system'

[target.x86_64-unknown-linux-gnu]
cc = "/usr/bin/clang"
cxx = "/usr/bin/clang++"
ar = "/usr/bin/llvm-ar"
ranlib = "/usr/bin/llvm-ranlib"
linker = "/usr/bin/clang"
llvm-config = "/usr/bin/llvm-config"
llvm-libunwind = 'system'