# Enable the D-Bus service (including its socket for socket activation) unconditionally
enable dbus.socket
enable dbus-broker.service

enable pipewire.socket
enable pipewire-pulse.socket
enable wireplumber.service

enable obex.service

# Enable mpris-proxy
enable mpris-proxy.service

# Ensure xdg-user-dirs are created properly
enable xdg-user-dirs.service
