#
# SPDX-FileCopyrightText: © 2020-2023 Serpent OS Developers
#
# SPDX-License-Identifier: Zlib
#
name        : docker-compose
version     : 2.17.2
release     : 3
homepage    : https://github.com/docker/compose
upstreams   :
    - https://github.com/docker/compose/archive/refs/tags/v2.17.2.tar.gz : d6e6de858ecdb0104991c86c66dde5dd4fb6a1160d707308d8ad3167450c8094
summary     : Define and run multi-container applications with Docker 
description : |
    Define and run multi-container applications with Docker 
license     :
    - Apache-2.0
networking  : yes
builddeps   :
    - binary(go)
environment : |
    export _compose_r=github.com/docker/compose
    export _cli_plugins_dir=%(libdir)/docker/cli-plugins
    export GO111MODULE=auto

    # This can probably be removed after golang reboostrap.
    export GOMODCACHE="%(workdir)/.cache"

    export GOFLAGS="-buildmode=pie -trimpath -mod=readonly -modcacherw -ldflags=-linkmode=external -ldflags=-X=$_compose_r/v2/internal.Version=v%(version)"

    # Git commit corresponding to the version tag
    export GITCOMMIT="0b6133f75b1678413a588a80440a3b239e686467"
    
    # https://github.com/serpent-os/boulder/issues/74
    export CGO_CFLAGS="${CFLAGS} -Wno-error=unused-command-line-argument"
build      : |
    go build -o docker-compose ./cmd/compose
install    : |
    %install_exe docker-compose -t %(installroot)/$_cli_plugins_dir
